### ISSUE TITLE
Password Change Fails

### ISSUE THREAD

**Issue by moebrowne** [FlamesRunner/FlamesCP-2#15]
The password change script (`password.php`) is sent the new password via `$_POST['newpassword']` but the query that writes to the db uses `$_POST['password']` so your password is set to blank.

**Comment by FlamesRunner** [comment]
I have fixed this in the 1b2cc7a commit.

**Comment by moebrowne** [comment]
@FlamesRunner Ah right, I was looking at the `develop` branch, might be worth merging `master` into `develop` so it's up to date?

**Comment by FlamesRunner** [comment]
Yep. I'll merge it when I can.
