### ISSUE TITLE
No Authentication Check For Console

### ISSUE THREAD

**Issue by moebrowne** [FlamesRunner/FlamesCP-2#18]
There is no check to see if the user is logged in when trying to accessing the console output script.

This means anyone who requests  `/console_output.php` will be able to see your logs!

**Comment by FlamesRunner** [comment]
I'm working on the fix right now. Thanks for reporting it!

**Comment by FlamesRunner** [comment]
This has been fixed with the b2268c5 commit.
Thanks again.
