### ISSUE TITLE
Weak password hashing

### ISSUE THREAD

**Issue by 1Conan** [FlamesRunner/FlamesCP-2#2]
You're using md5 which is already pretty much deprecated. 

I'd suggest bcrypt with a very long salt :D

**Comment by FlamesRunner** [comment]
I invite you to fix the issue - I've fixed the other ticket you've submitted.

**Comment by 1Conan** [comment]
I'll try to do it during my free time at school. Teachers dumped a few projects on us ahahha

**Comment by FlamesRunner** [comment]
Thanks :)

**Comment by FlamesRunner** [comment]
When you get time, please feel free to change the temporary SHA1 hashing system - but for now it has been resolved with the commit 738ece0.

**Comment by FlamesRunner** [comment]
No worries actually - I've changed the temporary hashing system to a salted crypt() for better security.

**Comment by 1Conan** [comment]
I'mlooking into adding a column for users in the mysql db for per user salts tho. 
Would be far more secure. 
(I gotta analyze your code for a while)

Also would you mind indenting your code? It's a bit hard to read on my phone :D

**Comment by FlamesRunner** [comment]
I'll have it done soon enough :)
