### ISSUE TITLE
Page Sessions

### ISSUE THREAD

**Issue by doghouch** [FlamesRunner/FlamesCP-2#9]
You should make it check i.e. if a username exists in the session, rather than checking if the logged_in variable is set.. The logged_in variable isn't necessary anyway - if a user is signed in:

- the "username" session is set

Also, you shouldn't only check for the rank once. If the rank changes, it will not reflect until the user signs out, and goes through "login.php" again. 

You should check each time the page changes, in case the rank/status changes, so updates reflect immediately.

**Comment by FlamesRunner** [comment]
The reason why ranks cannot change is because only the main administrator (with the user ID 0) can manipulate accounts. If the administrator removes a sub-account, that user should be automatically logged out.

As for the first part, I'll have that fixed.

Thanks.

**Comment by 1Conan** [comment]
@doghouch I honestly don't see anything wrong with having to logout to get the new rank.

**Comment by 1Conan** [comment]
Does #10 fix the "username checking" instead of "logged_in"?

**Comment by FlamesRunner** [comment]
Either way, I've fixed this in the commit 8a9afaa.
This issue ticket will be closed if it meets requirements.

**Comment by 1Conan** [comment]
Oh I forgot to check the includes :3
